apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-tracker
  namespace: student-tracker
  labels:
    app: student-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-tracker
  template:
    metadata:
      labels:
        app: student-tracker
    spec:
      containers:
        - name: student-tracker
          image: biwunor/student-tracker:latest
          ports:
            - containerPort: 8011  # ✅ FIXED to match your actual app port
          env:
            - name: VAULT_ADDR
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: VAULT_ADDR
            - name: VAULT_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: VAULT_ROLE_ID
            - name: VAULT_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: VAULT_SECRET_ID
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
