[build]
  command = "./build.sh"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.13"

# Environment variables for database and vault access
[build.environment]
  # Database Configuration
  DATABASE_URL = "mongodb://localhost:27017"
  DATABASE_NAME = "nativeseries"
  COLLECTION_NAME = "students"
  
  # Vault Configuration
  VAULT_ADDR = "http://44.204.193.107:8200"
  VAULT_ROLE_ID = ""
  VAULT_SECRET_ID = ""
  
  # Application Configuration
  APP_ENV = "production"
  APP_NAME = "NativeSeries"
  APP_VERSION = "1.0.0"
  SECRET_KEY = "your-secret-key-here"
  DEBUG = "false"
  LOG_LEVEL = "INFO"
  
  # MongoDB Configuration (if using external MongoDB)
  MONGO_URI = "mongodb://localhost:27017"
  
  # Security and CORS
  CORS_ORIGINS = "*"
  ALLOWED_HOSTS = "*"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api/health"
  status = 200

[[redirects]]
  from = "/docs"
  to = "/.netlify/functions/api/docs"
  status = 200

[[redirects]]
  from = "/openapi.json"
  to = "/.netlify/functions/api/openapi.json"
  status = 200

[[redirects]]
  from = "/api/stats"
  to = "/.netlify/functions/api/stats"
  status = 200

[[redirects]]
  from = "/api/database"
  to = "/.netlify/functions/api/database"
  status = 200

[[redirects]]
  from = "/api/vault"
  to = "/.netlify/functions/api/vault"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "uvicorn app.main:app --host 0.0.0.0 --port 8000"
  port = 8000
  publish = "public"

# Headers for better security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Function-specific configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"