[build]
  command = "./build.sh"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.13"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "uvicorn app.main:app --host 0.0.0.0 --port 8000"
  port = 8000
  publish = "public"