apiVersion: v2
name: NativeSeries
description: A Helm chart for deploying NativeSeries application with ArgoCD
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - python
  - fastapi
  - kubernetes
  - helm
  - argocd
  - student-management
home: https://github.com/bonaventuresimeon/NativeSeries
sources:
  - https://github.com/bonaventuresimeon/NativeSeries
maintainers:
  - name: Bonaventure Simeon
    email: contact@bonaventure.org.ng
# dependencies:
#   - name: mongodb
#     version: 13.9.4
#     repository: https://charts.bitnami.com/bitnami
#     condition: mongodb.enabled
#   - name: redis
#     version: 21.2.13
#     repository: https://charts.bitnami.com/bitnami
#     condition: redis.enabled