# Application configuration
app:
  name: student-tracker
  image:
    repository: ghcr.io/bonaventuresimeon/NativeSeries/student-tracker
    tag: latest
    pullPolicy: IfNotPresent
  env:
    - name: ENVIRONMENT
      value: "production"
    - name: MONGO_URI
      value: "mongodb://localhost:27017"
    - name: DATABASE_NAME
      value: "student_project_tracker"
    - name: COLLECTION_NAME
      value: "students"

# Service configuration
service:
  type: NodePort
  port: 8000
  targetPort: 8000
  nodePort: 8011

# Ingress configuration (disabled for direct IP deployment)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: student-tracker.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# MongoDB configuration (external)
mongodb:
  enabled: false

# Redis configuration (external)
redis:
  enabled: false

# Vault configuration (external)
vault:
  enabled: false

# ArgoCD configuration
argocd:
  enabled: false

# Horizontal Pod Autoscaler
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Resources
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Service monitor for Prometheus (requires Prometheus Operator)
serviceMonitor:
  enabled: false
  interval: 30s