# Application configuration
app:
  name: student-tracker
  image:
    repository: ghcr.io/bonaventuresimeon/NativeSeries/student-tracker
    tag: latest
    pullPolicy: IfNotPresent
  env:
    - name: ENVIRONMENT
      value: "production"
    - name: MONGO_URI
      value: "mongodb://localhost:27017"
    - name: DATABASE_NAME
      value: "student_project_tracker"
    - name: COLLECTION_NAME
      value: "students"

# Service configuration
service:
  type: NodePort
  port: 8000
  targetPort: 8000
  nodePort: 30011

# Enhanced Ingress configuration with TLS support
ingress:
  enabled: true  # Enable for production with proper domain
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: student-tracker.yourdomain.com  # Replace with your actual domain
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - student-tracker.yourdomain.com
      secretName: student-tracker-tls

# DNS and domain configuration
dns:
  enabled: true
  domain: student-tracker.yourdomain.com
  type: CNAME  # or A record depending on your setup

# MongoDB configuration (external)
mongodb:
  enabled: false

# Redis configuration (external)
redis:
  enabled: false

# Vault configuration (external)
vault:
  enabled: false

# ArgoCD configuration
argocd:
  enabled: true
  namespace: argocd
  server:
    type: LoadBalancer
    port: 80
  urls:
    production: "https://argocd-prod.yourdomain.com"
    development: "https://argocd-dev.yourdomain.com"
    staging: "https://argocd-staging.yourdomain.com"
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    hosts:
      - host: argocd-prod.yourdomain.com
        paths:
          - path: /
            pathType: Prefix
      - host: argocd-dev.yourdomain.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - argocd-prod.yourdomain.com
          - argocd-dev.yourdomain.com
        secretName: argocd-tls

# Enhanced Horizontal Pod Autoscaler
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15

# Enhanced Resources with better defaults
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Enhanced Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  capabilities:
    drop:
      - ALL

# Pod Security Standards
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

# Enhanced Service monitor for Prometheus
serviceMonitor:
  enabled: true
  interval: 30s
  path: /metrics
  port: http

# Network policies for enhanced security
networkPolicy:
  enabled: true
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8000

# Backup and disaster recovery
backup:
  enabled: false
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention: 7  # Keep 7 days of backups

# Monitoring and alerting
monitoring:
  enabled: true
  grafana:
    enabled: false
  prometheus:
    enabled: true
    retention: 15d