# Default values for student-tracker
# This is a YAML-formatted file.

# Application configuration
app:
  name: student-tracker
  port: 8000

# Image configuration
image:
  repository: student-tracker
  tag: latest
  pullPolicy: IfNotPresent

# Deployment configuration
replicaCount: 2

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Health checks
healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Service configuration
service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30011  # Maps to production port on the host

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: 54.166.101.159
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Environment variables
env:
  - name: DATABASE_URL
    value: "postgresql://user:pass@db:5432/studentdb"
  - name: APP_ENV
    value: "development"

# ConfigMap data
configMap:
  enabled: true
  data:
    app_name: "Student Tracker API"
    log_level: "INFO"

# Secret data (for sensitive information)
secret:
  enabled: false
  data: {}

# Pod Security Context
podSecurityContext:
  fsGroup: 2000

<<<<<<< HEAD
# Security Context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
=======
# Prometheus Rules for alerts
prometheusRules:
  enabled: true
  rules:
    - alert: AppDown
      expr: up{app="nativeseries"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Application is down"
    
    - alert: HighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{container="nativeseries"}[5m]) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage for {{ $labels.app }}"
        description: "CPU usage is above 80% for {{ $labels.app }}"
    
    - alert: HighMemoryUsage
      expr: (container_memory_usage_bytes{container="nativeseries"} / container_spec_memory_limit_bytes{container="nativeseries"}) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage for {{ $labels.app }}"
        description: "Memory usage is above 80% for {{ $labels.app }}"

# Logging configuration
logging:
  enabled: true
  loki:
    enabled: true
    url: "http://loki.logging:3100"
    labels:
      app: nativeseries
      namespace: nativeseries
  volume:
    enabled: true
    size: 1Gi
    mountPath: /app/logs

# Metrics configuration
metrics:
  enabled: true
  port: 8000
  path: /metrics
  interval: 30s
>>>>>>> d8bfc0ef6b6941753c17c3c17a9ab4a55611f139

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Horizontal Pod Autoscaler
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# ServiceMonitor for Prometheus (if using Prometheus Operator)
serviceMonitor:
  enabled: false
  interval: 30s
  path: /metrics
