apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nativeseries.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nativeseries.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nativeseries.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nativeseries.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- if .Values.vault.enabled }}
            - name: VAULT_ADDR
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: VAULT_ADDR
            - name: VAULT_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: VAULT_ROLE_ID
            - name: VAULT_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: VAULT_SECRET_ID
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}