apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: gitops
networking:
  kubeProxyMode: iptables
  apiServerAddress: "0.0.0.0"
nodes:
- role: control-plane
  image: kindest/node:v1.27.3
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 30011
    hostPort: 30011
    protocol: TCP
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
  - containerPort: 30081
    hostPort: 30081
    protocol: TCP
  - containerPort: 30082
    hostPort: 30082
    protocol: TCP
  - containerPort: 30083
    hostPort: 30083
    protocol: TCP
- role: worker
  image: kindest/node:v1.27.3
- role: worker
  image: kindest/node:v1.27.3