# Production environment values
replicaCount: 3

image:
  repository: student-tracker
  tag: stable
  pullPolicy: IfNotPresent

# Resource limits for production
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Production environment variables
env:
  - name: DATABASE_URL
    value: "postgresql://prod_user:prod_pass@postgres-prod:5432/studentdb_prod"
  - name: APP_ENV
    value: "production"
  - name: DEBUG
    value: "false"

# Ingress for production
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: student-tracker.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: student-tracker-tls
      hosts:
        - student-tracker.yourdomain.com

# Enable autoscaling in production
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Pod Disruption Budget for high availability
podDisruptionBudget:
  enabled: true
  minAvailable: 2

# ConfigMap for production
configMap:
  enabled: true
  data:
    app_name: "Student Tracker API"
    log_level: "INFO"

# Enhanced security context for production
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10001