replicaCount: 2

image:
  repository: simple-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000
  targetPort: 8000
  nodePort: 8011

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "8000"