replicaCount: 2

image:
  repository: ghcr.io/bonaventuresimeon/nativeseries
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8000
  targetPort: 8000
  nodePort: 30012

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "8000"
  - name: DATABASE_URL
    value: "sqlite:///./student_tracker.db"
  - name: REDIS_URL
    value: "redis://localhost:6379"

# Health checks
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Horizontal Pod Autoscaler
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Service account
serviceAccount:
  create: true
  name: "student-tracker-sa"

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000