replicaCount: 2

image:
  repository: biwunor/student-tracker
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 8011
  nodePort: 30012

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ec2-3-80-98-218.eu-west-1.compute.amazonaws.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Namespace configuration
namespace:
  create: true
  name: "student-tracker"

# Vault secrets configuration
vault:
  enabled: true
  secrets:
    VAULT_ADDR: "http://44.204.193.107:8200"
    VAULT_ROLE_ID: "f7af58b1-5c22-7c2d-c659-0425d9ce94b2"  
    VAULT_SECRET_ID: "d5f736da-785b-8f5c-9258-48d5d7c43c06"

env:
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "8011"

# Health checks
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Horizontal Pod Autoscaler
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Service account
serviceAccount:
  create: true
  name: "student-tracker-sa"

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000