apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "student-tracker.fullname" . }}-config
  labels:
    {{- include "student-tracker.labels" . | nindent 4 }}
data:
  app.conf: |
    [app]
    name = {{ .Values.app.name }}
    environment = production
    
    [vault]
    addr = http://vault:8200
    
    [mongodb]
    database = student_project_tracker
    
    [redis]
    url = redis://redis:6379/0
    
    [logging]
    level = INFO
    format = json