{{- if .Values.configMaps.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.appConfig.name }}
  labels:
    {{- include "nativeseries.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMaps.appConfig.data | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.loggingConfig.name }}
  labels:
    {{- include "nativeseries.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMaps.loggingConfig.data | nindent 2 }}
{{- end }}