apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "student-tracker.fullname" . }}-config
  labels:
    {{- include "student-tracker.labels" . | nindent 4 }}
data:
  app.conf: |
    [app]
    name = {{ .Values.app.name }}
    environment = {{ .Values.app.env | first | default "production" }}
    
    [database]
    url = postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql:5432/myapp
    
    [redis]
    url = redis://redis:6379/0
    
    [logging]
    level = INFO
    format = json