apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app.fullname" . }}-config
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
data:
  app.conf: |
    [app]
    name = {{ .Values.app.name }}
    environment = {{ .Values.app.env | pluck "value" | first | default "production" }}
    
    [database]
    url = {{ .Values.app.env | pluck "value" | first | default "postgresql://localhost:5432/myapp" }}
    
    [redis]
    url = {{ .Values.app.env | pluck "value" | first | default "redis://localhost:6379/0" }}
    
    [logging]
    level = INFO
    format = json