apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "student-tracker.fullname" . }}-config
  labels:
    {{- include "student-tracker.labels" . | nindent 4 }}
data:
  app.conf: |
    [app]
    name = {{ .Values.app.name }}
    environment = production
    
    [database]
    type = in-memory
    
    [logging]
    level = INFO
    format = json