{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nativeseries.fullname" . }}-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nativeseries.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nativeseries.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{- range .Values.networkPolicy.ingress }}
  - from:
    {{- toYaml .from | nindent 4 }}
    ports:
    {{- toYaml .ports | nindent 4 }}
  {{- end }}
  egress:
  {{- range .Values.networkPolicy.egress }}
  - to:
    {{- toYaml .to | nindent 4 }}
    ports:
    {{- toYaml .ports | nindent 4 }}
  {{- end }}
{{- end }}