{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "student-tracker.fullname" . }}
  labels:
    {{- include "student-tracker.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "student-tracker.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- range .Values.networkPolicy.ingress }}
    - from:
        {{- toYaml .from | nindent 8 }}
      ports:
        {{- toYaml .ports | nindent 8 }}
    {{- end }}
    # Allow health checks from kubelet
    - ports:
        - protocol: TCP
          port: 8000
      from: []
  egress:
    # Allow DNS resolution
    - ports:
        - protocol: UDP
          port: 53
      to:
        - namespaceSelector: {}
    # Allow HTTPS for external API calls
    - ports:
        - protocol: TCP
          port: 443
      to:
        - namespaceSelector: {}
    # Allow HTTP for external API calls (if needed)
    - ports:
        - protocol: TCP
          port: 80
      to:
        - namespaceSelector: {}
{{- end }}