apiVersion: v1
kind: Service
metadata:
  name: {{ include "nativeseries.fullname" . }}
  labels:
    {{- include "nativeseries.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
<<<<<<< HEAD
    {{- include "student-tracker.selectorLabels" . | nindent 4 }}
=======
    {{- include "nativeseries.selectorLabels" . | nindent 4 }}
>>>>>>> f2475f83ae74981450743dfeecb4ab0d29f50a37
