apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nativeseries
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: nativeseries
    app.kubernetes.io/part-of: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bonaventuresimeon/nativeseries.git
    targetRevision: HEAD
    path: helm-chart
    helm:
      values: |
        image:
          repository: ghcr.io/bonaventuresimeon/nativeseries
          tag: latest
        service:
          type: NodePort
          nodePort: 30011
        ingress:
          enabled: false
        networkPolicy:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: nativeseries
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
