replicaCount: 3

image:
  repository: biwunor/student-tracker
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8011

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: student-tracker.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: student-tracker-tls
      hosts:
        - student-tracker.yourdomain.com
