apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-tracker-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/student-tracker.git  # Update with your repo URL
    targetRevision: HEAD
    path: infra/helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
